### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by strozykowski** [violet-isle/mern-stack#1]
Add a [README.md file to the top-level directory structure](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes) to describe the project and give additional information to the potential user.

Things to include:
- [ ] Project Title
- [ ] Project Purpose
- [ ] Architecture description
  - [ ] Frontend technology design
  - [ ] Backend technology design
  - [ ] Database design
  - [ ] Backup strategy
  - [ ] (Optional) Include [mermaid diagrams](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams)
- [ ] Prerequisites for installation
- [ ] Installation steps
- [ ] Copyright/license information

Be sure to:
- [ ] Use clear language to describe the project
- [ ] Follow the document outline model (e.g. level 1 headings -> level 2, so there is a clear outline)

**Comment by violet-isle** [comment]
Added README! Thanks.
